language: python

python:
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "3.6"


before_install:
  - cp README.md README.rst

install:
  - pip install -e .

script: python -c "import nanolyse"

notifications:
  email: false
  webhooks:
    urls:
        - https://webhooks.gitter.im/e/4b1c45cea6826ce475c2
